/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Polkadot',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Overview',
          link: {type:'doc', id:'polkadot/overview/index'},
          items: [
            'polkadot/overview/polkadot-introduction',
            'polkadot/overview/token-economics',
            'polkadot/overview/parachain-allocation',
          ],
        },
        {
          type: 'category',
          label: 'Protocols',
          link: {type:'doc', id:'polkadot/protocols/index'},
          items: [
            {
              type: 'category',
              label: 'Nominated Proof-of-Stake',
              link: {type:'doc', id:'polkadot/protocols/NPoS/index'},
              items: [
                'polkadot/protocols/NPoS/Overview',
                'polkadot/protocols/NPoS/Paper',
                'polkadot/protocols/NPoS/Balancing',
              ],
            },
            {
              type: 'category',
              label: 'Block production',
              link: {type:'doc', id:'polkadot/protocols/block-production/index'},
              items: [
                'polkadot/protocols/block-production/Babe',
                'polkadot/protocols/block-production/SASSAFRAS',
              ],
            },
            'polkadot/protocols/finality',
            'polkadot/protocols/LightClientsBridges',
          ],
        },
        {
          type: 'category',
          label: 'Economics',
          link: {type:'doc', id:'polkadot/economics/index'},
          items: [
            'polkadot/economics/validator-selection',
            'polkadot/economics/parachain-theory',
            'polkadot/economics/parachain-experiment',
            'polkadot/economics/gamification',
            'polkadot/economics/utilitytokendesign',
          ],
        },
        {
          type: 'category',
          label: 'Security',
          link: {type:'doc', id:'polkadot/security/index'},
          items: [
            {
              type: 'category',
              label: 'Keys',
              link: {type:'doc', id:'polkadot/security/keys/index'},
              items: [
                'polkadot/security/keys/accounts',
                'polkadot/security/keys/accounts-more',
                'polkadot/security/keys/staking',
                'polkadot/security/keys/session',
                'polkadot/security/keys/creation',
              ],
            },
            {
              type: 'category',
              label: 'Slashing',
              items: [
                'polkadot/security/slashing/amounts',
                'polkadot/security/slashing/npos',
              ],
            },
          ],
        },
      ]
    },
    {
      type: 'category',
      label: 'Cryptography',
      link: {type:'doc', id:'crypto/index'},
      collapsed: false,
      items: [
        'crypto/multisig',
        'crypto/LightClientBridgesindex',
      ],
    },
    {
      type: 'doc',
      id: 'news',
    },
    {
      type: 'doc',
      id: 'Publications',
    },
    {
      type: 'category',
      label: 'Team Members',
      link: {type:'doc', id:'team_members/index'},
      items: [
        'team_members/alfonso',
        'team_members/alistair',
        'team_members/handan',
        'team_members/jeff',
        'team_members/Jonas',
        'team_members/Oana',
        'team_members/Sergey',
        'team_members/syed',
      ],
    },
  ],
};

module.exports = sidebars;
