/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    {
      type: 'doc',
      id: 'research',
    },
    {
      type: 'category',
      label: 'Team Members',
      link: {type:'doc', id:'team_members/index'},
      items: [
        'team_members/alistair',
        'team_members/Andrew',
        'team_members/elizabeth',
        'team_members/jeff',
        'team_members/Jonas',
        'team_members/Sergey',
        'team_members/syed',
        'team_members/chenda',
        'team_members/Bhargav'
      ],
    },
    {
      type: 'doc',
      id: 'Publications',
    },
  ],
};

module.exports = sidebars;
