version: 2

jobs:
  tests:
    docker:
      - image: python:3.8-buster
    steps:
      - checkout
      - run:
          name: build
          command: |
            apt-get update
            apt-get install -y graphviz
            pip install virtualenv

            python3.8 -mvirtualenv --no-download .

            source bin/activate

            pip install sphinx sphinx-serve
            pip install -r docs/requirements.txt

            sphinx-build -b html docs _build/html
      - run:
          name: serve
          background: true
          command: |
            source bin/activate

            sphinx-serve -p 8000

      - run:
          name: check links
          command: |
            pip install pylinkvalidator html5lib

            sed -i -e 's/\(decode("ascii")\)/\1.replace(" ", "%20")/g' /usr/local/lib/python3.8/site-packages/pylinkvalidator/urlutil.py

            pylinkvalidate.py --parser=html5lib -P http://localhost:8000


workflows:
  version: 2
  build_and_test:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
